### PR TITLE
enable codecov.io

### PR DESCRIPTION
**Pull request by andriisoldatenko**

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@ryw  how can i check why Snyk is falling? i'm still don't have access.

**Comment by schnie** [comment]
@andriisoldatenko do we need to worry about snyk warning?

**Comment by ryw** [comment]
just re-invited you @andriisoldatenko

**Comment by andriisoldatenko** [comment]
:( same issue.

**Comment by andriisoldatenko** [comment]
@schnie i think we are good to go now, on separately i'll email snyk support.

**Pull request merged**
